'use client';

import { useEffect, useState } from 'react';
import Giscus from '@giscus/react';

/**
 * Giscus-backed comments.
 *
 * Anti-spam strategy:
 *  - Giscus requires a GitHub login → blocks scriptable bots.
 *  - `mapping="pathname"` + `strict=1` so each post pins to one Discussion (no spoofed creation).
 *  - `reactionsEnabled={0}` keeps drive-by reaction-spam off; commenters must write something.
 *  - In the GitHub repo, also recommended:
 *      • Settings → Moderation options → Interaction limits ("Limit to users existing for >24h" or "prior contributors").
 *      • Discussions → Category settings → require maintainers' approval for first-time contributors.
 *      • Block disposable-email users via GitHub's own protections.
 */

const GISCUS = {
  repo: 'ififi2017/ififi2017.github.io' as `${string}/${string}`,
  /* Generated by giscus.app for this repo and the "Comments" discussion category.
     If either ID is removed, render a maintenance note instead of a broken iframe. */
  repoId: 'MDEwOlJlcG9zaXRvcnkzNTEzNzY2NTg=',
  category: 'Comments',
  categoryId: 'DIC_kwDOFPGVEs4C9OQr',
};

export default function Comments() {
  const [theme, setTheme] = useState<'light' | 'dark_dimmed'>('light');

  useEffect(() => {
    const sync = () => {
      const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
      setTheme(isDark ? 'dark_dimmed' : 'light');
    };
    sync();
    const observer = new MutationObserver(sync);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
    return () => observer.disconnect();
  }, []);

  const configured = GISCUS.repoId && GISCUS.categoryId;

  return (
    <section className="rk-comments">
      <div className="rk-comments-head">
        <div className="rk-section-tag">COMMENTS</div>
        <h3 className="rk-section-title">留言</h3>
        <p className="rk-comments-sub">
          评论存储在 GitHub Discussions。需要登录 GitHub。
        </p>
      </div>

      {configured ? (
        <Giscus
          id="comments"
          repo={GISCUS.repo}
          repoId={GISCUS.repoId}
          category={GISCUS.category}
          categoryId={GISCUS.categoryId}
          mapping="pathname"
          strict="1"
          reactionsEnabled="0"
          emitMetadata="0"
          inputPosition="top"
          theme={theme}
          lang="zh-CN"
          loading="lazy"
        />
      ) : (
        <div className="rk-comments-setup">
          <p>
            <strong>评论系统暂不可用。</strong>
            请检查 <code>{GISCUS.repo}</code> 是否仍已安装 giscus App，并确认 Discussions
            与 <code>Comments</code> 分类可用。
          </p>
          <p>
            如需重新生成配置，到 <code>https://giscus.app</code> 选择该仓库和
            <code>Comments</code> 分类，然后更新 <code>repoId</code> / <code>categoryId</code> 常量。
          </p>
        </div>
      )}
    </section>
  );
}
