'use client';

import { useEffect, useState } from 'react';
import Giscus from '@giscus/react';

/**
 * Giscus-backed comments.
 *
 * Anti-spam strategy:
 *  - Giscus requires a GitHub login → blocks scriptable bots.
 *  - `mapping="pathname"` + `strict=1` so each post pins to one Discussion (no spoofed creation).
 *  - `reactionsEnabled={0}` keeps drive-by reaction-spam off; commenters must write something.
 *  - In the GitHub repo, also recommended:
 *      • Settings → Moderation options → Interaction limits ("Limit to users existing for >24h" or "prior contributors").
 *      • Discussions → Category settings → require maintainers' approval for first-time contributors.
 *      • Block disposable-email users via GitHub's own protections.
 */

const GISCUS = {
  repo: 'ififi2017/ififi2017.github.io' as `${string}/${string}`,
  /* Generated by giscus.app for the repo above — owner needs to install the giscus App
     and paste the resulting IDs here. The empty defaults render a clear instructions panel
     instead of a broken iframe. */
  repoId: 'MDEwOlJlcG9zaXRvcnkzNTEzNzY2NTg=',
  category: 'Comments',
  categoryId: 'DIC_kwDOFPGVEs4C9OQr',
};

export default function Comments() {
  const [theme, setTheme] = useState<'light' | 'dark_dimmed'>('light');

  useEffect(() => {
    const sync = () => {
      const isDark = document.documentElement.getAttribute('data-theme') === 'dark';
      setTheme(isDark ? 'dark_dimmed' : 'light');
    };
    sync();
    const observer = new MutationObserver(sync);
    observer.observe(document.documentElement, { attributes: true, attributeFilter: ['data-theme'] });
    return () => observer.disconnect();
  }, []);

  const configured = GISCUS.repoId && GISCUS.categoryId;

  return (
    <section className="rk-comments">
      <div className="rk-comments-head">
        <div className="rk-section-tag">COMMENTS</div>
        <h3 className="rk-section-title">留言</h3>
        <p className="rk-comments-sub">
          评论存储在 GitHub Discussions。需要登录 GitHub。
        </p>
      </div>

      {configured ? (
        <Giscus
          id="comments"
          repo={GISCUS.repo}
          repoId={GISCUS.repoId}
          category={GISCUS.category}
          categoryId={GISCUS.categoryId}
          mapping="pathname"
          strict="1"
          reactionsEnabled="0"
          emitMetadata="0"
          inputPosition="top"
          theme={theme}
          lang="zh-CN"
          loading="lazy"
        />
      ) : (
        <div className="rk-comments-setup">
          <p>
            <strong>评论系统待激活。</strong>
            到 <code>https://giscus.app</code> 配置仓库
            <code>{GISCUS.repo}</code>，将得到的
            <code>repo-id</code> 与 <code>category-id</code> 写入环境变量
            <code>NEXT_PUBLIC_GISCUS_REPO_ID</code> / <code>NEXT_PUBLIC_GISCUS_CATEGORY_ID</code>
            （或者直接改 <code>components/Comments.tsx</code> 里的常量）。
          </p>
          <p>
            激活前请同时在 GitHub 仓库里开启 Discussions、创建
            <code>Comments</code> 分类，并按需启用 Interaction limits 防机器人。
          </p>
        </div>
      )}
    </section>
  );
}
